name: Test Environment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v5

      - name: 2. Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '22'
          cache: 'gradle'


      - name: 3. Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
            gradle-version: 8.8


      - name: 3. Start Docker
        working-directory: gradlerepo
        run: |
            docker compose -f src/test/resources/docker/docker-compose.testcontainer.yml down -v
            docker compose -f src/test/resources/docker/docker-compose.testcontainer.yml up -d --wait

      - name: 4. Grant execute permission
        working-directory: gradlerepo
        run: chmod +x gradlew

      
      - name: 5. Run Tests
        working-directory: gradlerepo
        run: gradle test --tests "com.gradleproject.data.OrderTestIT"



      - name: 7. Generate Allure Report
        if: always()
        working-directory: gradlerepo
        run: gradle allureReport

      - name: 8. Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: gradlerepo/build/allure-results

      - name: 9. Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: gradlerepo/build/reports/allure-report/allureReport
